services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - composer-cache:/tmp/composer
    environment:
      - COMPOSER_CACHE_DIR=/tmp/composer
    ports:
      - "8080:80"
    networks:
      - limesurvey-net
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - limesurvey-net

  selenium:
    image: selenium/standalone-firefox:3.141.59-20210929
    ports:
      - "4444:4444"
    networks:
      - limesurvey-net

networks:
  limesurvey-net:

volumes:
  postgres-data:
  composer-cache:
